spring.application.name=vendedor-service
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=vendedor
spring.mongodb.uri=mongodb://localhost:27017/teste
spring.jackson.mapper.sort-properties-alphabetically=false
integration.filial.url=http://localhost:8089
spring.web.error.include-message=always
spring.web.error.include-stacktrace=always
spring.web.error.include-binding-errors=always
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-retries=2
spring.rabbitmq.listener.simple.retry.initial-interval=5000
spring.rabbitmq.listener.simple.retry.multiplier=1
spring.rabbitmq.listener.simple.retry.max-interval=300000